package eslint

// Code generated by scripts/gen_builtin.js from eslint@8.57.0 — DO NOT EDIT.
//
// RecommendedRules is the eslint:recommended rule set (every rule module whose
// meta.docs.recommended is true), DeprecatedRules maps the rules eslint marks
// deprecated to their replacements (meta.replacedBy), and RuleReplacements is
// eslint/conf/replacements.json, which turns the missing-rule message into a
// "was removed and replaced by" message for rules eslint deleted.

// RecommendedRules maps rule id to the severity eslint:recommended gives it.
var RecommendedRules = map[string]any{
	"constructor-super":             "error",
	"for-direction":                 "error",
	"getter-return":                 "error",
	"no-async-promise-executor":     "error",
	"no-case-declarations":          "error",
	"no-class-assign":               "error",
	"no-compare-neg-zero":           "error",
	"no-cond-assign":                "error",
	"no-const-assign":               "error",
	"no-constant-condition":         "error",
	"no-control-regex":              "error",
	"no-debugger":                   "error",
	"no-delete-var":                 "error",
	"no-dupe-args":                  "error",
	"no-dupe-class-members":         "error",
	"no-dupe-else-if":               "error",
	"no-dupe-keys":                  "error",
	"no-duplicate-case":             "error",
	"no-empty-character-class":      "error",
	"no-empty-pattern":              "error",
	"no-empty":                      "error",
	"no-ex-assign":                  "error",
	"no-extra-boolean-cast":         "error",
	"no-extra-semi":                 "error",
	"no-fallthrough":                "error",
	"no-func-assign":                "error",
	"no-global-assign":              "error",
	"no-import-assign":              "error",
	"no-inner-declarations":         "error",
	"no-invalid-regexp":             "error",
	"no-irregular-whitespace":       "error",
	"no-loss-of-precision":          "error",
	"no-misleading-character-class": "error",
	"no-mixed-spaces-and-tabs":      "error",
	"no-new-symbol":                 "error",
	"no-nonoctal-decimal-escape":    "error",
	"no-obj-calls":                  "error",
	"no-octal":                      "error",
	"no-prototype-builtins":         "error",
	"no-redeclare":                  "error",
	"no-regex-spaces":               "error",
	"no-self-assign":                "error",
	"no-setter-return":              "error",
	"no-shadow-restricted-names":    "error",
	"no-sparse-arrays":              "error",
	"no-this-before-super":          "error",
	"no-undef":                      "error",
	"no-unexpected-multiline":       "error",
	"no-unreachable":                "error",
	"no-unsafe-finally":             "error",
	"no-unsafe-negation":            "error",
	"no-unsafe-optional-chaining":   "error",
	"no-unused-labels":              "error",
	"no-unused-vars":                "error",
	"no-useless-backreference":      "error",
	"no-useless-catch":              "error",
	"no-useless-escape":             "error",
	"no-with":                       "error",
	"require-yield":                 "error",
	"use-isnan":                     "error",
	"valid-typeof":                  "error",
}

// DeprecatedRules maps a deprecated built-in rule id to its replacemente list
// (empty when eslint names none).
var DeprecatedRules = map[string][]string{
	"array-bracket-newline":            {},
	"array-bracket-spacing":            {},
	"array-element-newline":            {},
	"arrow-parens":                     {},
	"arrow-spacing":                    {},
	"block-spacing":                    {},
	"brace-style":                      {},
	"callback-return":                  {},
	"comma-dangle":                     {},
	"comma-spacing":                    {},
	"comma-style":                      {},
	"computed-property-spacing":        {},
	"dot-location":                     {},
	"eol-last":                         {},
	"func-call-spacing":                {},
	"function-call-argument-newline":   {},
	"function-paren-newline":           {},
	"generator-star-spacing":           {},
	"global-require":                   {},
	"handle-callback-err":              {},
	"id-blacklist":                     {"id-denylist"},
	"implicit-arrow-linebreak":         {},
	"indent":                           {},
	"indent-legacy":                    {"indent"},
	"jsx-quotes":                       {},
	"key-spacing":                      {},
	"keyword-spacing":                  {},
	"linebreak-style":                  {},
	"lines-around-comment":             {},
	"lines-around-directive":           {"padding-line-between-statements"},
	"lines-between-class-members":      {},
	"max-len":                          {},
	"max-statements-per-line":          {},
	"multiline-ternary":                {},
	"new-parens":                       {},
	"newline-after-var":                {"padding-line-between-statements"},
	"newline-before-return":            {"padding-line-between-statements"},
	"newline-per-chained-call":         {},
	"no-buffer-constructor":            {},
	"no-catch-shadow":                  {"no-shadow"},
	"no-confusing-arrow":               {},
	"no-extra-parens":                  {},
	"no-extra-semi":                    {},
	"no-floating-decimal":              {},
	"no-mixed-operators":               {},
	"no-mixed-requires":                {},
	"no-mixed-spaces-and-tabs":         {},
	"no-multi-spaces":                  {},
	"no-multiple-empty-lines":          {},
	"no-native-reassign":               {"no-global-assign"},
	"no-negated-in-lhs":                {"no-unsafe-negation"},
	"no-new-object":                    {"no-object-constructor"},
	"no-new-require":                   {},
	"no-path-concat":                   {},
	"no-process-env":                   {},
	"no-process-exit":                  {},
	"no-restricted-modules":            {},
	"no-return-await":                  {},
	"no-spaced-func":                   {"func-call-spacing"},
	"no-sync":                          {},
	"no-tabs":                          {},
	"no-trailing-spaces":               {},
	"no-whitespace-before-property":    {},
	"nonblock-statement-body-position": {},
	"object-curly-newline":             {},
	"object-curly-spacing":             {},
	"object-property-newline":          {},
	"one-var-declaration-per-line":     {},
	"operator-linebreak":               {},
	"padded-blocks":                    {},
	"padding-line-between-statements":  {},
	"prefer-reflect":                   {},
	"quote-props":                      {},
	"quotes":                           {},
	"require-jsdoc":                    {},
	"rest-spread-spacing":              {},
	"semi":                             {},
	"semi-spacing":                     {},
	"semi-style":                       {},
	"space-before-blocks":              {},
	"space-before-function-paren":      {},
	"space-in-parens":                  {},
	"space-infix-ops":                  {},
	"space-unary-ops":                  {},
	"spaced-comment":                   {},
	"switch-colon-spacing":             {},
	"template-curly-spacing":           {},
	"template-tag-spacing":             {},
	"valid-jsdoc":                      {},
	"wrap-iife":                        {},
	"wrap-regex":                       {},
	"yield-star-spacing":               {},
}

// BuiltinGlobals are the ES5 builtin globals ESLint's eslintrc Linter path
// defines for every file, whatever parserOptions.ecmaVersion says (verified by
// probing every es5/es2015+ name through eslint 8.57: 38/38 es5 names are
// defined, while Map, Promise, globalThis, WeakRef, … are not).
var BuiltinGlobals = map[string]string{"Array": "readonly", "Boolean": "readonly", "Date": "readonly", "Error": "readonly", "EvalError": "readonly", "Function": "readonly", "Infinity": "readonly", "JSON": "readonly", "Math": "readonly", "NaN": "readonly", "Number": "readonly", "Object": "readonly", "RangeError": "readonly", "ReferenceError": "readonly", "RegExp": "readonly", "String": "readonly", "SyntaxError": "readonly", "TypeError": "readonly", "URIError": "readonly", "constructor": "readonly", "decodeURI": "readonly", "decodeURIComponent": "readonly", "encodeURI": "readonly", "encodeURIComponent": "readonly", "escape": "readonly", "eval": "readonly", "hasOwnProperty": "readonly", "isFinite": "readonly", "isNaN": "readonly", "isPrototypeOf": "readonly", "parseFloat": "readonly", "parseInt": "readonly", "propertyIsEnumerable": "readonly", "toLocaleString": "readonly", "toString": "readonly", "undefined": "readonly", "unescape": "readonly", "valueOf": "readonly"}

// EcmaVersionGlobals is eslint's per-ecmaVersion global table
// (conf/globals.js), keyed by the year form ("es2022", …). Carried for
// auditing only: this port must NOT apply it, because the reference
// implementation does not (see BuiltinGlobals).
var EcmaVersionGlobals = map[string]map[string]string{
	"es2015": {"Array": "readonly", "ArrayBuffer": "readonly", "Boolean": "readonly", "DataView": "readonly", "Date": "readonly", "Error": "readonly", "EvalError": "readonly", "Float32Array": "readonly", "Float64Array": "readonly", "Function": "readonly", "Infinity": "readonly", "Int16Array": "readonly", "Int32Array": "readonly", "Int8Array": "readonly", "JSON": "readonly", "Map": "readonly", "Math": "readonly", "NaN": "readonly", "Number": "readonly", "Object": "readonly", "Promise": "readonly", "Proxy": "readonly", "RangeError": "readonly", "ReferenceError": "readonly", "Reflect": "readonly", "RegExp": "readonly", "Set": "readonly", "String": "readonly", "Symbol": "readonly", "SyntaxError": "readonly", "TypeError": "readonly", "URIError": "readonly", "Uint16Array": "readonly", "Uint32Array": "readonly", "Uint8Array": "readonly", "Uint8ClampedArray": "readonly", "WeakMap": "readonly", "WeakSet": "readonly", "constructor": "readonly", "decodeURI": "readonly", "decodeURIComponent": "readonly", "encodeURI": "readonly", "encodeURIComponent": "readonly", "escape": "readonly", "eval": "readonly", "hasOwnProperty": "readonly", "isFinite": "readonly", "isNaN": "readonly", "isPrototypeOf": "readonly", "parseFloat": "readonly", "parseInt": "readonly", "propertyIsEnumerable": "readonly", "toLocaleString": "readonly", "toString": "readonly", "undefined": "readonly", "unescape": "readonly", "valueOf": "readonly"},
	"es2016": {"Array": "readonly", "ArrayBuffer": "readonly", "Boolean": "readonly", "DataView": "readonly", "Date": "readonly", "Error": "readonly", "EvalError": "readonly", "Float32Array": "readonly", "Float64Array": "readonly", "Function": "readonly", "Infinity": "readonly", "Int16Array": "readonly", "Int32Array": "readonly", "Int8Array": "readonly", "JSON": "readonly", "Map": "readonly", "Math": "readonly", "NaN": "readonly", "Number": "readonly", "Object": "readonly", "Promise": "readonly", "Proxy": "readonly", "RangeError": "readonly", "ReferenceError": "readonly", "Reflect": "readonly", "RegExp": "readonly", "Set": "readonly", "String": "readonly", "Symbol": "readonly", "SyntaxError": "readonly", "TypeError": "readonly", "URIError": "readonly", "Uint16Array": "readonly", "Uint32Array": "readonly", "Uint8Array": "readonly", "Uint8ClampedArray": "readonly", "WeakMap": "readonly", "WeakSet": "readonly", "constructor": "readonly", "decodeURI": "readonly", "decodeURIComponent": "readonly", "encodeURI": "readonly", "encodeURIComponent": "readonly", "escape": "readonly", "eval": "readonly", "hasOwnProperty": "readonly", "isFinite": "readonly", "isNaN": "readonly", "isPrototypeOf": "readonly", "parseFloat": "readonly", "parseInt": "readonly", "propertyIsEnumerable": "readonly", "toLocaleString": "readonly", "toString": "readonly", "undefined": "readonly", "unescape": "readonly", "valueOf": "readonly"},
	"es2017": {"Array": "readonly", "ArrayBuffer": "readonly", "Atomics": "readonly", "Boolean": "readonly", "DataView": "readonly", "Date": "readonly", "Error": "readonly", "EvalError": "readonly", "Float32Array": "readonly", "Float64Array": "readonly", "Function": "readonly", "Infinity": "readonly", "Int16Array": "readonly", "Int32Array": "readonly", "Int8Array": "readonly", "JSON": "readonly", "Map": "readonly", "Math": "readonly", "NaN": "readonly", "Number": "readonly", "Object": "readonly", "Promise": "readonly", "Proxy": "readonly", "RangeError": "readonly", "ReferenceError": "readonly", "Reflect": "readonly", "RegExp": "readonly", "Set": "readonly", "SharedArrayBuffer": "readonly", "String": "readonly", "Symbol": "readonly", "SyntaxError": "readonly", "TypeError": "readonly", "URIError": "readonly", "Uint16Array": "readonly", "Uint32Array": "readonly", "Uint8Array": "readonly", "Uint8ClampedArray": "readonly", "WeakMap": "readonly", "WeakSet": "readonly", "constructor": "readonly", "decodeURI": "readonly", "decodeURIComponent": "readonly", "encodeURI": "readonly", "encodeURIComponent": "readonly", "escape": "readonly", "eval": "readonly", "hasOwnProperty": "readonly", "isFinite": "readonly", "isNaN": "readonly", "isPrototypeOf": "readonly", "parseFloat": "readonly", "parseInt": "readonly", "propertyIsEnumerable": "readonly", "toLocaleString": "readonly", "toString": "readonly", "undefined": "readonly", "unescape": "readonly", "valueOf": "readonly"},
	"es2018": {"Array": "readonly", "ArrayBuffer": "readonly", "Atomics": "readonly", "Boolean": "readonly", "DataView": "readonly", "Date": "readonly", "Error": "readonly", "EvalError": "readonly", "Float32Array": "readonly", "Float64Array": "readonly", "Function": "readonly", "Infinity": "readonly", "Int16Array": "readonly", "Int32Array": "readonly", "Int8Array": "readonly", "JSON": "readonly", "Map": "readonly", "Math": "readonly", "NaN": "readonly", "Number": "readonly", "Object": "readonly", "Promise": "readonly", "Proxy": "readonly", "RangeError": "readonly", "ReferenceError": "readonly", "Reflect": "readonly", "RegExp": "readonly", "Set": "readonly", "SharedArrayBuffer": "readonly", "String": "readonly", "Symbol": "readonly", "SyntaxError": "readonly", "TypeError": "readonly", "URIError": "readonly", "Uint16Array": "readonly", "Uint32Array": "readonly", "Uint8Array": "readonly", "Uint8ClampedArray": "readonly", "WeakMap": "readonly", "WeakSet": "readonly", "constructor": "readonly", "decodeURI": "readonly", "decodeURIComponent": "readonly", "encodeURI": "readonly", "encodeURIComponent": "readonly", "escape": "readonly", "eval": "readonly", "hasOwnProperty": "readonly", "isFinite": "readonly", "isNaN": "readonly", "isPrototypeOf": "readonly", "parseFloat": "readonly", "parseInt": "readonly", "propertyIsEnumerable": "readonly", "toLocaleString": "readonly", "toString": "readonly", "undefined": "readonly", "unescape": "readonly", "valueOf": "readonly"},
	"es2019": {"Array": "readonly", "ArrayBuffer": "readonly", "Atomics": "readonly", "Boolean": "readonly", "DataView": "readonly", "Date": "readonly", "Error": "readonly", "EvalError": "readonly", "Float32Array": "readonly", "Float64Array": "readonly", "Function": "readonly", "Infinity": "readonly", "Int16Array": "readonly", "Int32Array": "readonly", "Int8Array": "readonly", "JSON": "readonly", "Map": "readonly", "Math": "readonly", "NaN": "readonly", "Number": "readonly", "Object": "readonly", "Promise": "readonly", "Proxy": "readonly", "RangeError": "readonly", "ReferenceError": "readonly", "Reflect": "readonly", "RegExp": "readonly", "Set": "readonly", "SharedArrayBuffer": "readonly", "String": "readonly", "Symbol": "readonly", "SyntaxError": "readonly", "TypeError": "readonly", "URIError": "readonly", "Uint16Array": "readonly", "Uint32Array": "readonly", "Uint8Array": "readonly", "Uint8ClampedArray": "readonly", "WeakMap": "readonly", "WeakSet": "readonly", "constructor": "readonly", "decodeURI": "readonly", "decodeURIComponent": "readonly", "encodeURI": "readonly", "encodeURIComponent": "readonly", "escape": "readonly", "eval": "readonly", "hasOwnProperty": "readonly", "isFinite": "readonly", "isNaN": "readonly", "isPrototypeOf": "readonly", "parseFloat": "readonly", "parseInt": "readonly", "propertyIsEnumerable": "readonly", "toLocaleString": "readonly", "toString": "readonly", "undefined": "readonly", "unescape": "readonly", "valueOf": "readonly"},
	"es2020": {"Array": "readonly", "ArrayBuffer": "readonly", "Atomics": "readonly", "BigInt": "readonly", "BigInt64Array": "readonly", "BigUint64Array": "readonly", "Boolean": "readonly", "DataView": "readonly", "Date": "readonly", "Error": "readonly", "EvalError": "readonly", "Float32Array": "readonly", "Float64Array": "readonly", "Function": "readonly", "Infinity": "readonly", "Int16Array": "readonly", "Int32Array": "readonly", "Int8Array": "readonly", "JSON": "readonly", "Map": "readonly", "Math": "readonly", "NaN": "readonly", "Number": "readonly", "Object": "readonly", "Promise": "readonly", "Proxy": "readonly", "RangeError": "readonly", "ReferenceError": "readonly", "Reflect": "readonly", "RegExp": "readonly", "Set": "readonly", "SharedArrayBuffer": "readonly", "String": "readonly", "Symbol": "readonly", "SyntaxError": "readonly", "TypeError": "readonly", "URIError": "readonly", "Uint16Array": "readonly", "Uint32Array": "readonly", "Uint8Array": "readonly", "Uint8ClampedArray": "readonly", "WeakMap": "readonly", "WeakSet": "readonly", "constructor": "readonly", "decodeURI": "readonly", "decodeURIComponent": "readonly", "encodeURI": "readonly", "encodeURIComponent": "readonly", "escape": "readonly", "eval": "readonly", "globalThis": "readonly", "hasOwnProperty": "readonly", "isFinite": "readonly", "isNaN": "readonly", "isPrototypeOf": "readonly", "parseFloat": "readonly", "parseInt": "readonly", "propertyIsEnumerable": "readonly", "toLocaleString": "readonly", "toString": "readonly", "undefined": "readonly", "unescape": "readonly", "valueOf": "readonly"},
	"es2021": {"AggregateError": "readonly", "Array": "readonly", "ArrayBuffer": "readonly", "Atomics": "readonly", "BigInt": "readonly", "BigInt64Array": "readonly", "BigUint64Array": "readonly", "Boolean": "readonly", "DataView": "readonly", "Date": "readonly", "Error": "readonly", "EvalError": "readonly", "FinalizationRegistry": "readonly", "Float32Array": "readonly", "Float64Array": "readonly", "Function": "readonly", "Infinity": "readonly", "Int16Array": "readonly", "Int32Array": "readonly", "Int8Array": "readonly", "JSON": "readonly", "Map": "readonly", "Math": "readonly", "NaN": "readonly", "Number": "readonly", "Object": "readonly", "Promise": "readonly", "Proxy": "readonly", "RangeError": "readonly", "ReferenceError": "readonly", "Reflect": "readonly", "RegExp": "readonly", "Set": "readonly", "SharedArrayBuffer": "readonly", "String": "readonly", "Symbol": "readonly", "SyntaxError": "readonly", "TypeError": "readonly", "URIError": "readonly", "Uint16Array": "readonly", "Uint32Array": "readonly", "Uint8Array": "readonly", "Uint8ClampedArray": "readonly", "WeakMap": "readonly", "WeakRef": "readonly", "WeakSet": "readonly", "constructor": "readonly", "decodeURI": "readonly", "decodeURIComponent": "readonly", "encodeURI": "readonly", "encodeURIComponent": "readonly", "escape": "readonly", "eval": "readonly", "globalThis": "readonly", "hasOwnProperty": "readonly", "isFinite": "readonly", "isNaN": "readonly", "isPrototypeOf": "readonly", "parseFloat": "readonly", "parseInt": "readonly", "propertyIsEnumerable": "readonly", "toLocaleString": "readonly", "toString": "readonly", "undefined": "readonly", "unescape": "readonly", "valueOf": "readonly"},
	"es2022": {"AggregateError": "readonly", "Array": "readonly", "ArrayBuffer": "readonly", "Atomics": "readonly", "BigInt": "readonly", "BigInt64Array": "readonly", "BigUint64Array": "readonly", "Boolean": "readonly", "DataView": "readonly", "Date": "readonly", "Error": "readonly", "EvalError": "readonly", "FinalizationRegistry": "readonly", "Float32Array": "readonly", "Float64Array": "readonly", "Function": "readonly", "Infinity": "readonly", "Int16Array": "readonly", "Int32Array": "readonly", "Int8Array": "readonly", "JSON": "readonly", "Map": "readonly", "Math": "readonly", "NaN": "readonly", "Number": "readonly", "Object": "readonly", "Promise": "readonly", "Proxy": "readonly", "RangeError": "readonly", "ReferenceError": "readonly", "Reflect": "readonly", "RegExp": "readonly", "Set": "readonly", "SharedArrayBuffer": "readonly", "String": "readonly", "Symbol": "readonly", "SyntaxError": "readonly", "TypeError": "readonly", "URIError": "readonly", "Uint16Array": "readonly", "Uint32Array": "readonly", "Uint8Array": "readonly", "Uint8ClampedArray": "readonly", "WeakMap": "readonly", "WeakRef": "readonly", "WeakSet": "readonly", "constructor": "readonly", "decodeURI": "readonly", "decodeURIComponent": "readonly", "encodeURI": "readonly", "encodeURIComponent": "readonly", "escape": "readonly", "eval": "readonly", "globalThis": "readonly", "hasOwnProperty": "readonly", "isFinite": "readonly", "isNaN": "readonly", "isPrototypeOf": "readonly", "parseFloat": "readonly", "parseInt": "readonly", "propertyIsEnumerable": "readonly", "toLocaleString": "readonly", "toString": "readonly", "undefined": "readonly", "unescape": "readonly", "valueOf": "readonly"},
	"es2023": {"AggregateError": "readonly", "Array": "readonly", "ArrayBuffer": "readonly", "Atomics": "readonly", "BigInt": "readonly", "BigInt64Array": "readonly", "BigUint64Array": "readonly", "Boolean": "readonly", "DataView": "readonly", "Date": "readonly", "Error": "readonly", "EvalError": "readonly", "FinalizationRegistry": "readonly", "Float32Array": "readonly", "Float64Array": "readonly", "Function": "readonly", "Infinity": "readonly", "Int16Array": "readonly", "Int32Array": "readonly", "Int8Array": "readonly", "JSON": "readonly", "Map": "readonly", "Math": "readonly", "NaN": "readonly", "Number": "readonly", "Object": "readonly", "Promise": "readonly", "Proxy": "readonly", "RangeError": "readonly", "ReferenceError": "readonly", "Reflect": "readonly", "RegExp": "readonly", "Set": "readonly", "SharedArrayBuffer": "readonly", "String": "readonly", "Symbol": "readonly", "SyntaxError": "readonly", "TypeError": "readonly", "URIError": "readonly", "Uint16Array": "readonly", "Uint32Array": "readonly", "Uint8Array": "readonly", "Uint8ClampedArray": "readonly", "WeakMap": "readonly", "WeakRef": "readonly", "WeakSet": "readonly", "constructor": "readonly", "decodeURI": "readonly", "decodeURIComponent": "readonly", "encodeURI": "readonly", "encodeURIComponent": "readonly", "escape": "readonly", "eval": "readonly", "globalThis": "readonly", "hasOwnProperty": "readonly", "isFinite": "readonly", "isNaN": "readonly", "isPrototypeOf": "readonly", "parseFloat": "readonly", "parseInt": "readonly", "propertyIsEnumerable": "readonly", "toLocaleString": "readonly", "toString": "readonly", "undefined": "readonly", "unescape": "readonly", "valueOf": "readonly"},
	"es2024": {"AggregateError": "readonly", "Array": "readonly", "ArrayBuffer": "readonly", "Atomics": "readonly", "BigInt": "readonly", "BigInt64Array": "readonly", "BigUint64Array": "readonly", "Boolean": "readonly", "DataView": "readonly", "Date": "readonly", "Error": "readonly", "EvalError": "readonly", "FinalizationRegistry": "readonly", "Float32Array": "readonly", "Float64Array": "readonly", "Function": "readonly", "Infinity": "readonly", "Int16Array": "readonly", "Int32Array": "readonly", "Int8Array": "readonly", "JSON": "readonly", "Map": "readonly", "Math": "readonly", "NaN": "readonly", "Number": "readonly", "Object": "readonly", "Promise": "readonly", "Proxy": "readonly", "RangeError": "readonly", "ReferenceError": "readonly", "Reflect": "readonly", "RegExp": "readonly", "Set": "readonly", "SharedArrayBuffer": "readonly", "String": "readonly", "Symbol": "readonly", "SyntaxError": "readonly", "TypeError": "readonly", "URIError": "readonly", "Uint16Array": "readonly", "Uint32Array": "readonly", "Uint8Array": "readonly", "Uint8ClampedArray": "readonly", "WeakMap": "readonly", "WeakRef": "readonly", "WeakSet": "readonly", "constructor": "readonly", "decodeURI": "readonly", "decodeURIComponent": "readonly", "encodeURI": "readonly", "encodeURIComponent": "readonly", "escape": "readonly", "eval": "readonly", "globalThis": "readonly", "hasOwnProperty": "readonly", "isFinite": "readonly", "isNaN": "readonly", "isPrototypeOf": "readonly", "parseFloat": "readonly", "parseInt": "readonly", "propertyIsEnumerable": "readonly", "toLocaleString": "readonly", "toString": "readonly", "undefined": "readonly", "unescape": "readonly", "valueOf": "readonly"},
	"es5":    {"Array": "readonly", "Boolean": "readonly", "Date": "readonly", "Error": "readonly", "EvalError": "readonly", "Function": "readonly", "Infinity": "readonly", "JSON": "readonly", "Math": "readonly", "NaN": "readonly", "Number": "readonly", "Object": "readonly", "RangeError": "readonly", "ReferenceError": "readonly", "RegExp": "readonly", "String": "readonly", "SyntaxError": "readonly", "TypeError": "readonly", "URIError": "readonly", "constructor": "readonly", "decodeURI": "readonly", "decodeURIComponent": "readonly", "encodeURI": "readonly", "encodeURIComponent": "readonly", "escape": "readonly", "eval": "readonly", "hasOwnProperty": "readonly", "isFinite": "readonly", "isNaN": "readonly", "isPrototypeOf": "readonly", "parseFloat": "readonly", "parseInt": "readonly", "propertyIsEnumerable": "readonly", "toLocaleString": "readonly", "toString": "readonly", "undefined": "readonly", "unescape": "readonly", "valueOf": "readonly"},
}

// CommonJSGlobals are added when parserOptions.sourceType is "commonjs".
var CommonJSGlobals = map[string]string{"exports": "writable", "global": "readonly", "module": "readonly", "require": "readonly"}

// RuleReplacements maps a removed rule id to the rules that replaced it.
var RuleReplacements = map[string][]string{
	"generator-star":                    {"generator-star-spacing"},
	"global-strict":                     {"strict"},
	"no-arrow-condition":                {"no-confusing-arrow", "no-constant-condition"},
	"no-comma-dangle":                   {"comma-dangle"},
	"no-empty-class":                    {"no-empty-character-class"},
	"no-empty-label":                    {"no-labels"},
	"no-extra-strict":                   {"strict"},
	"no-reserved-keys":                  {"quote-props"},
	"no-space-before-semi":              {"semi-spacing"},
	"no-wrap-func":                      {"no-extra-parens"},
	"space-after-function-name":         {"space-before-function-paren"},
	"space-after-keywords":              {"keyword-spacing"},
	"space-before-function-parentheses": {"space-before-function-paren"},
	"space-before-keywords":             {"keyword-spacing"},
	"space-in-brackets":                 {"object-curly-spacing", "array-bracket-spacing", "computed-property-spacing"},
	"space-return-throw-case":           {"keyword-spacing"},
	"space-unary-word-ops":              {"space-unary-ops"},
	"spaced-line-comment":               {"spaced-comment"},
}

// MissingRuleMessage reproduces linter.js's createMissingRuleMessage.
func MissingRuleMessage(ruleID string) string {
	if replaced, ok := RuleReplacements[ruleID]; ok {
		return "Rule '" + ruleID + "' was removed and replaced by: " + joinComma(replaced)
	}
	return "Definition for rule '" + ruleID + "' was not found."
}

func joinComma(items []string) string {
	out := ""
	for i, s := range items {
		if i > 0 {
			out += ", "
		}
		out += s
	}
	return out
}
