package eslint

// visitorKeys maps each ESTree node type to its child keys for traversal.
// Transcribed from eslint-visitor-keys (the canonical keys ESLint's Traverser
// uses). Program/Program body coverage is what the starter rules rely on.
var visitorKeys = map[string][]string{
	"AssignmentExpression":     {"left", "right"},
	"AssignmentPattern":        {"left", "right"},
	"ArrayExpression":          {"elements"},
	"ArrayPattern":             {"elements"},
	"ArrowFunctionExpression":  {"params", "body"},
	"AwaitExpression":          {"argument"},
	"BlockStatement":           {"body"},
	"BinaryExpression":         {"left", "right"},
	"BreakStatement":           {"label"},
	"CallExpression":           {"callee", "arguments"},
	"CatchClause":              {"param", "body"},
	"ChainExpression":          {"expression"},
	"ClassBody":                {"body"},
	"ClassDeclaration":         {"id", "superClass", "body"},
	"ClassExpression":          {"id", "superClass", "body"},
	"ConditionalExpression":    {"test", "consequent", "alternate"},
	"ContinueStatement":        {"label"},
	"DebuggerStatement":        {},
	"DirectiveStatement":       {},
	"DoWhileStatement":         {"body", "test"},
	"EmptyStatement":           {},
	"ExportAllDeclaration":     {"exported", "source"},
	"ExportDefaultDeclaration": {"declaration"},
	"ExportNamedDeclaration":   {"declaration", "specifiers", "source"},
	"ExportSpecifier":          {"exported", "local"},
	"ExpressionStatement":      {"expression"},
	"ForStatement":             {"init", "test", "update", "body"},
	"ForInStatement":           {"left", "right", "body"},
	"ForOfStatement":           {"left", "right", "body"},
	"FunctionDeclaration":      {"id", "params", "body"},
	"FunctionExpression":       {"id", "params", "body"},
	"Identifier":               {},
	"IfStatement":              {"test", "consequent", "alternate"},
	"ImportDeclaration":        {"specifiers", "source"},
	"ImportDefaultSpecifier":   {"local"},
	"ImportNamespaceSpecifier": {"local"},
	"ImportSpecifier":          {"imported", "local"},
	"Literal":                  {},
	"LabeledStatement":         {"label", "body"},
	"LogicalExpression":        {"left", "right"},
	"MemberExpression":         {"object", "property"},
	"MetaProperty":             {"meta", "property"},
	"MethodDefinition":         {"decorators", "key", "value"},
	"NewExpression":            {"callee", "arguments"},
	"ObjectExpression":         {"properties"},
	"ObjectPattern":            {"properties"},
	"PrivateIdentifier":        {},
	"Program":                  {"body"},
	"Property":                 {"key", "value"},
	"PropertyDefinition":       {"decorators", "key", "value"},
	"RestElement":              {"argument"},
	"ReturnStatement":          {"argument"},
	"SequenceExpression":       {"expressions"},
	"SpreadElement":            {"argument"},
	"Super":                    {},
	"SwitchStatement":          {"discriminant", "cases"},
	"SwitchCase":               {"test", "consequent"},
	"TaggedTemplateExpression": {"tag", "quasi"},
	"TemplateElement":          {},
	"TemplateLiteral":          {"quasis", "expressions"},
	"ThisExpression":           {},
	"ThrowStatement":           {"argument"},
	"TryStatement":             {"block", "handler", "finalizer"},
	"UnaryExpression":          {"argument"},
	"UpdateExpression":         {"argument"},
	"VariableDeclaration":      {"declarations"},
	"VariableDeclarator":       {"id", "init"},
	"WhileStatement":           {"test", "body"},
	"WithStatement":            {"object", "body"},
	"YieldExpression":          {"argument"},
}
