'use strict';
// gen_builtin.js — generates builtin.go from the installed eslint@8.57.0:
//
//  * RecommendedRules — the `eslint:recommended` set, derived the same way
//    @eslint/eslintrc derives it (rule modules whose meta.docs.recommended is
//    true), all mapped to "error".
//  * DeprecatedRules — rules whose meta.deprecated is true, mapped to their
//    meta.replacedBy list. ESLint's CLI reports these per file as
//    `usedDeprecatedRules`.
//  * RuleReplacements — eslint/conf/replacements.json, used for the
//    "was removed and replaced by" variant of the missing-rule message.
//
// Run from the eslint-go repo root: node scripts/gen_builtin.js
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const rulesDir = path.join(process.cwd(), 'oracle/node_modules/eslint/lib/rules');

const recommended = [];
const deprecated = {};
for (const file of fs.readdirSync(rulesDir).sort()) {
    if (!file.endsWith('.js') || file.startsWith('index')) continue;
    const id = file.slice(0, -3);
    let mod;
    try {
        mod = require(path.join(rulesDir, file));
    } catch (e) {
        continue;
    }
    if (!mod || !mod.meta) continue;
    if (mod.meta.docs && mod.meta.docs.recommended === true) {
        recommended.push(id);
    }
    if (mod.meta.deprecated === true) {
        deprecated[id] = Array.isArray(mod.meta.replacedBy) ? mod.meta.replacedBy : [];
    }
}

const replacements = JSON.parse(
    fs.readFileSync(path.join(process.cwd(), 'oracle/node_modules/eslint/conf/replacements.json'), 'utf8')
).rules;

// Built-in globals ESLint injects per ecmaVersion/sourceType (conf/globals.js,
// consumed by SourceCode.applyLanguageOptions via getGlobalsForEcmaVersion).
const envGlobals = require(path.join(process.cwd(), 'oracle/node_modules/eslint/conf/globals.js'));
const versionKeys = Object.keys(envGlobals).filter(k => k.startsWith('es') && k !== 'es3').sort();

function access(value) {
    if (value === 'writable' || value === true) return 'writable';
    return 'readonly';
}

const versionLines = versionKeys
    .map(key => {
        const entries = Object.keys(envGlobals[key])
            .sort()
            .map(name => `${JSON.stringify(name)}:${JSON.stringify(access(envGlobals[key][name]))}`)
            .join(', ');
        return `\t"${key}": {${entries}},`;
    })
    .join('\n');

const eslintPkg = require(path.join(process.cwd(), 'oracle/node_modules/eslint/package.json'));

const ruleLines = recommended.map(id => `\t${JSON.stringify(id)}: "error",`).join('\n');
const depLines = Object.keys(deprecated)
    .sort()
    .map(id => `\t${JSON.stringify(id)}: {${deprecated[id].map(x => JSON.stringify(x)).join(', ')}},`)
    .join('\n');
const replLines = Object.keys(replacements)
    .sort()
    .map(id => `\t${JSON.stringify(id)}: {${replacements[id].map(x => JSON.stringify(x)).join(', ')}},`)
    .join('\n');

const commonJS = Object.keys(envGlobals.commonjs)
    .sort()
    .map(name => `${JSON.stringify(name)}:${JSON.stringify(access(envGlobals.commonjs[name]))}`)
    .join(', ');

// ESLint's eslintrc Linter path defines exactly the ES5 builtin globals
// (conf/globals.js es5) regardless of parserOptions.ecmaVersion: probing every
// name in es5 and es2015+ through the 8.57 Linter shows all 38 es5 names
// defined and all 28 later names (Map, Promise, globalThis, WeakRef, …)
// undefined. env/browser/node globals then layer on top of that base.
const builtins = Object.keys(envGlobals.es5)
    .sort()
    .map(name => `${JSON.stringify(name)}:${JSON.stringify(access(envGlobals.es5[name]))}`)
    .join(', ');

const file = `package eslint

// Code generated by scripts/gen_builtin.js from eslint@${eslintPkg.version} — DO NOT EDIT.
//
// RecommendedRules is the eslint:recommended rule set (every rule module whose
// meta.docs.recommended is true), DeprecatedRules maps the rules eslint marks
// deprecated to their replacements (meta.replacedBy), and RuleReplacements is
// eslint/conf/replacements.json, which turns the missing-rule message into a
// "was removed and replaced by" message for rules eslint deleted.

// RecommendedRules maps rule id to the severity eslint:recommended gives it.
var RecommendedRules = map[string]any{
${ruleLines}
}

// DeprecatedRules maps a deprecated built-in rule id to its replacemente list
// (empty when eslint names none).
var DeprecatedRules = map[string][]string{
${depLines}
}

// BuiltinGlobals are the ES5 builtin globals ESLint's eslintrc Linter path
// defines for every file, whatever parserOptions.ecmaVersion says (verified by
// probing every es5/es2015+ name through eslint 8.57: 38/38 es5 names are
// defined, while Map, Promise, globalThis, WeakRef, … are not).
var BuiltinGlobals = map[string]string{${builtins}}

// EcmaVersionGlobals is eslint's per-ecmaVersion global table
// (conf/globals.js), keyed by the year form ("es2022", …). Carried for
// auditing only: this port must NOT apply it, because the reference
// implementation does not (see BuiltinGlobals).
var EcmaVersionGlobals = map[string]map[string]string{
${versionLines}
}

// CommonJSGlobals are added when parserOptions.sourceType is "commonjs".
var CommonJSGlobals = map[string]string{${commonJS}}

// RuleReplacements maps a removed rule id to the rules that replaced it.
var RuleReplacements = map[string][]string{
${replLines}
}

// MissingRuleMessage reproduces linter.js's createMissingRuleMessage.
func MissingRuleMessage(ruleID string) string {
	if replaced, ok := RuleReplacements[ruleID]; ok {
		return "Rule '" + ruleID + "' was removed and replaced by: " + joinComma(replaced)
	}
	return "Definition for rule '" + ruleID + "' was not found."
}

func joinComma(items []string) string {
	out := ""
	for i, s := range items {
		if i > 0 {
			out += ", "
		}
		out += s
	}
	return out
}
`;

const target = path.join(process.cwd(), 'builtin.go');
fs.writeFileSync(target, file);
execFileSync('gofmt', ['-w', target], { stdio: 'inherit' });
console.log(
    `wrote ${target}: ${recommended.length} recommended rules, ${Object.keys(deprecated).length} deprecated, ` +
        `${Object.keys(replacements).length} replacements`
);
