'use strict';
// gen_builtin.js — generates builtin.go from the installed eslint@8.57.0:
//
//  * RecommendedRules — the `eslint:recommended` set, derived the same way
//    @eslint/eslintrc derives it (rule modules whose meta.docs.recommended is
//    true), all mapped to "error".
//  * DeprecatedRules — rules whose meta.deprecated is true, mapped to their
//    meta.replacedBy list. ESLint's CLI reports these per file as
//    `usedDeprecatedRules`.
//  * RuleReplacements — eslint/conf/replacements.json, used for the
//    "was removed and replaced by" variant of the missing-rule message.
//
// Run from the eslint-go repo root: node scripts/gen_builtin.js
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const rulesDir = path.join(process.cwd(), 'oracle/node_modules/eslint/lib/rules');

const recommended = [];
const deprecated = {};
for (const file of fs.readdirSync(rulesDir).sort()) {
    if (!file.endsWith('.js') || file.startsWith('index')) continue;
    const id = file.slice(0, -3);
    let mod;
    try {
        mod = require(path.join(rulesDir, file));
    } catch (e) {
        continue;
    }
    if (!mod || !mod.meta) continue;
    if (mod.meta.docs && mod.meta.docs.recommended === true) {
        recommended.push(id);
    }
    if (mod.meta.deprecated === true) {
        deprecated[id] = Array.isArray(mod.meta.replacedBy) ? mod.meta.replacedBy : [];
    }
}

const replacements = JSON.parse(
    fs.readFileSync(path.join(process.cwd(), 'oracle/node_modules/eslint/conf/replacements.json'), 'utf8')
).rules;

const eslintPkg = require(path.join(process.cwd(), 'oracle/node_modules/eslint/package.json'));

const ruleLines = recommended.map(id => `\t${JSON.stringify(id)}: "error",`).join('\n');
const depLines = Object.keys(deprecated)
    .sort()
    .map(id => `\t${JSON.stringify(id)}: {${deprecated[id].map(x => JSON.stringify(x)).join(', ')}},`)
    .join('\n');
const replLines = Object.keys(replacements)
    .sort()
    .map(id => `\t${JSON.stringify(id)}: {${replacements[id].map(x => JSON.stringify(x)).join(', ')}},`)
    .join('\n');

const file = `package eslint

// Code generated by scripts/gen_builtin.js from eslint@${eslintPkg.version} — DO NOT EDIT.
//
// RecommendedRules is the eslint:recommended rule set (every rule module whose
// meta.docs.recommended is true), DeprecatedRules maps the rules eslint marks
// deprecated to their replacements (meta.replacedBy), and RuleReplacements is
// eslint/conf/replacements.json, which turns the missing-rule message into a
// "was removed and replaced by" message for rules eslint deleted.

// RecommendedRules maps rule id to the severity eslint:recommended gives it.
var RecommendedRules = map[string]any{
${ruleLines}
}

// DeprecatedRules maps a deprecated built-in rule id to its replacemente list
// (empty when eslint names none).
var DeprecatedRules = map[string][]string{
${depLines}
}

// RuleReplacements maps a removed rule id to the rules that replaced it.
var RuleReplacements = map[string][]string{
${replLines}
}

// MissingRuleMessage reproduces linter.js's createMissingRuleMessage.
func MissingRuleMessage(ruleID string) string {
	if replaced, ok := RuleReplacements[ruleID]; ok {
		return "Rule '" + ruleID + "' was removed and replaced by: " + joinComma(replaced)
	}
	return "Definition for rule '" + ruleID + "' was not found."
}

func joinComma(items []string) string {
	out := ""
	for i, s := range items {
		if i > 0 {
			out += ", "
		}
		out += s
	}
	return out
}
`;

const target = path.join(process.cwd(), 'builtin.go');
fs.writeFileSync(target, file);
execFileSync('gofmt', ['-w', target], { stdio: 'inherit' });
console.log(
    `wrote ${target}: ${recommended.length} recommended rules, ${Object.keys(deprecated).length} deprecated, ` +
        `${Object.keys(replacements).length} replacements`
);
