#!/usr/bin/env python3
"""Generate rules/registry_gen.go — the list of ported rules the CLI registers.

Only rules that have a parity test with at least one case are registered: a rule
without an oracle-verified test is not "ported" and would silently lint with
unverified behaviour, so it stays out of the registry (and a config that
references it reports the same missing-rule problem ESLint reports).

  python3 scripts/gen_rule_registry.py          # check
  python3 scripts/gen_rule_registry.py --write  # regenerate
"""
import argparse
import subprocess
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
RULES = ROOT / "rules"
TARGET = RULES / "registry_gen.go"
NAME_RE = re.compile(r'const Name = "([^"]+)"')
CASE_RE = re.compile(r'\bID:\s*"')


def count_cases(text):
    """Count the case literals a test file actually runs.

    Cases are `{ID: "..."}` entries in the slice handed to ruletest.Compare, so
    a whole-line comment is not a case: several corpora keep a commented-out
    entry as a note about a known gap (e.g. `// NOTE (core gap 3): {ID: ...}`),
    and counting those inflates the published figure. Comparing this count to
    the runtime "N cases, 0 mismatches" line per rule is what caught it.
    """
    live = [ln for ln in text.splitlines() if not ln.lstrip().startswith("//")]
    return len(CASE_RE.findall("\n".join(live)))


def discover():
    entries = []
    for pkg in sorted(p for p in RULES.iterdir() if p.is_dir()):
        go = pkg / f"{pkg.name}.go"
        if not go.exists():
            continue
        m = NAME_RE.search(go.read_text())
        if not m:
            continue
        tests = list(pkg.glob("*_test.go"))
        cases = sum(count_cases(t.read_text()) for t in tests)
        entries.append((pkg.name, m.group(1), cases))
    return entries


def render(entries):
    verified = [e for e in entries if e[2] > 0]
    lines = [
        "package rules",
        "",
        "// Code generated by scripts/gen_rule_registry.py — DO NOT EDIT.",
        "//",
        "// Only rules with an oracle-parity test carrying at least one case are",
        "// registered; the case count is the size of each rule's verified corpus.",
        "",
        "import (",
        '\teslint "github.com/jclyons52/eslint-go"',
    ]
    for pkg, _rule, _cases in verified:
        lines.append(f'\t"github.com/jclyons52/eslint-go/rules/{pkg}"')
    lines.append(")")
    lines.append("")
    lines.append("// registry is every ported rule, generated from rules/*/.")
    lines.append("var registry = []eslint.Rule{")
    for pkg, rule_id, cases in verified:
        lines.append(f"\t{pkg}.Rule, // {rule_id}: {cases} oracle cases")
    lines.append("}")
    lines.append("")
    lines.append("// unverified lists rule packages that are present but have no parity test")
    lines.append("// yet, so they are deliberately not registered.")
    lines.append("var unverified = []string{")
    for pkg, rule_id, cases in entries:
        if cases == 0:
            lines.append(f'\t"{rule_id} (rules/{pkg})",')
    lines.append("}")
    lines.append("")
    return "\n".join(lines), verified, [e for e in entries if e[2] == 0]


def gofmt(src):
    """Return src formatted by gofmt (a no-op passthrough if gofmt is absent)."""
    try:
        res = subprocess.run(["gofmt"], input=src, capture_output=True, text=True)
    except OSError:
        return src
    return res.stdout if res.returncode == 0 and res.stdout else src


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true")
    args = ap.parse_args()

    entries = discover()
    body, verified, unverified = render(entries)
    total = sum(c for _, _, c in verified)

    if args.write:
        # Keep the generated file gofmt-clean: the repo's CI gate runs
        # `gofmt -l .`, and a generated file that fails it blocks everything.
        # The formatted text is what both the write and the freshness check use.
        body = gofmt(body)
        TARGET.write_text(body)
        print(
            f"wrote {TARGET.name}: {len(verified)} verified rules "
            f"({total} oracle cases), {len(unverified)} unverified"
        )
        return 0

    if not TARGET.exists() or TARGET.read_text() != gofmt(body):
        print("rules/registry_gen.go is stale; re-run with --write", file=sys.stderr)
        return 1
    print(f"registry up to date: {len(verified)} rules, {total} oracle cases")
    if unverified:
        print("unverified: " + ", ".join(f"{r}" for _, r, _ in unverified))
    return 0


if __name__ == "__main__":
    sys.exit(main())
