'use strict';
// gen_env_globals.js — generates globals_env.go from the exact data ESLint 8
// uses for `env`: @eslint/eslintrc's Legacy.environments (which wraps the
// `globals` npm package).
//
// Run from the eslint-go repo root with the oracle's node_modules available:
//   node scripts/gen_env_globals.js
const fs = require('fs');
const path = require('path');

const eslintDir = process.env.ESLINT_ORACLE || './oracle/node_modules/eslint';
const eslintrc = require(path.join(process.cwd(), 'oracle/node_modules/@eslint/eslintrc'));
const eslintrcPkg = require(path.join(process.cwd(), 'oracle/node_modules/@eslint/eslintrc/package.json'));
const globalsPkg = require(path.join(process.cwd(), 'oracle/node_modules/globals/package.json'));

const environments = eslintrc.Legacy.environments;
const out = {};
const envNames = [];
const envOptions = {};

for (const [envId, env] of environments.entries()) {
    if (!env || !env.globals) continue;
    const names = {};
    for (const [name, value] of Object.entries(env.globals)) {
        if (value === 'off') continue;
        names[name] = (value === 'writable' || value === true) ? 'writable' : 'readonly';
    }
    out[envId] = names;
    envNames.push(envId);

    // An environment can also carry parserOptions. This matters: `env: node`
    // contributes ecmaFeatures.globalReturn, which makes espree allow top-level
    // `return` and makes eslint-scope nest a function scope over the Program —
    // so top-level declarations do not collide with node's globals.
    if (env.parserOptions && Object.keys(env.parserOptions).length > 0) {
        envOptions[envId] = env.parserOptions;
    }
}

envNames.sort();
const ordered = {};
for (const id of envNames) ordered[id] = out[id];

const json = JSON.stringify(ordered);
const optionsJSON = JSON.stringify(envOptions);

const file = `package eslint

// Code generated by scripts/gen_env_globals.js — DO NOT EDIT.
//
// Environment globals for the \`env\` config key, taken from
// @eslint/eslintrc@${eslintrcPkg.version} Legacy.environments (${environments.size} envs),
// which is what ESLint 8 uses; its data comes from the globals npm package
// (globals@${globalsPkg.version}).
//
// Values are "readonly" / "writable", matching ConfigOps.normalizeConfigGlobal.

import (
	"encoding/json"
	"sort"
	"sync"
)

// envGlobalsJSON is the env → {global name → access} table as JSON.
const envGlobalsJSON = \`${json}\`

// envParserOptionsJSON is the env → parserOptions table as JSON. Only
// environments that carry parserOptions appear (\`node\` is the one that matters:
// ecmaFeatures.globalReturn).
const envParserOptionsJSON = \`${optionsJSON}\`

var (
	envGlobalsOnce sync.Once
	envGlobalsData map[string]map[string]string
	envOptionsData map[string]map[string]any
)

func loadEnvTables() {
	envGlobalsOnce.Do(func() {
		envGlobalsData = map[string]map[string]string{}
		if err := json.Unmarshal([]byte(envGlobalsJSON), &envGlobalsData); err != nil {
			panic("eslint: invalid embedded env globals: " + err.Error())
		}
		envOptionsData = map[string]map[string]any{}
		if err := json.Unmarshal([]byte(envParserOptionsJSON), &envOptionsData); err != nil {
			panic("eslint: invalid embedded env parserOptions: " + err.Error())
		}
	})
}

// EnvGlobals returns the globals an environment contributes (name → access),
// or nil for an unknown environment.
func EnvGlobals(env string) map[string]string {
	loadEnvTables()
	return envGlobalsData[env]
}

// EnvParserOptions returns the parserOptions an environment contributes, or nil
// when the environment contributes none.
func EnvParserOptions(env string) map[string]any {
	loadEnvTables()
	return envOptionsData[env]
}

// EnvNames returns the supported environment ids (sorted).
func EnvNames() []string {
	EnvGlobals("") // ensure the table is loaded
	out := make([]string, 0, len(envGlobalsData))
	for id := range envGlobalsData {
		out = append(out, id)
	}
	sort.Strings(out)
	return out
}
`;

const target = path.join(process.cwd(), 'globals_env.go');
fs.writeFileSync(target, file);
let total = 0;
for (const id of envNames) total += Object.keys(ordered[id]).length;
console.log(`wrote ${target}: ${envNames.length} envs, ${total} global entries, ${json.length} bytes`);
