package rules

// Code generated by scripts/gen_rule_registry.py — DO NOT EDIT.
//
// Only rules with an oracle-parity test carrying at least one case are
// registered; the case count is the size of each rule's verified corpus.

import (
	eslint "github.com/jclyons52/eslint-go"
	"github.com/jclyons52/eslint-go/rules/commadangle"
	"github.com/jclyons52/eslint-go/rules/curly"
	"github.com/jclyons52/eslint-go/rules/dotnotation"
	"github.com/jclyons52/eslint-go/rules/eollast"
	"github.com/jclyons52/eslint-go/rules/eqeqeq"
	"github.com/jclyons52/eslint-go/rules/noalert"
	"github.com/jclyons52/eslint-go/rules/noarrayconstructor"
	"github.com/jclyons52/eslint-go/rules/nocaller"
	"github.com/jclyons52/eslint-go/rules/nocondassign"
	"github.com/jclyons52/eslint-go/rules/noconsole"
	"github.com/jclyons52/eslint-go/rules/nodebugger"
	"github.com/jclyons52/eslint-go/rules/nodupeargs"
	"github.com/jclyons52/eslint-go/rules/nodupekeys"
	"github.com/jclyons52/eslint-go/rules/noduplicatecase"
	"github.com/jclyons52/eslint-go/rules/noelsereturn"
	"github.com/jclyons52/eslint-go/rules/noempty"
	"github.com/jclyons52/eslint-go/rules/noeval"
	"github.com/jclyons52/eslint-go/rules/noextrabooleancast"
	"github.com/jclyons52/eslint-go/rules/noextrasemi"
	"github.com/jclyons52/eslint-go/rules/nofloatingdecimal"
	"github.com/jclyons52/eslint-go/rules/nofuncassign"
	"github.com/jclyons52/eslint-go/rules/nolonelyif"
	"github.com/jclyons52/eslint-go/rules/nomixedspacesandtabs"
	"github.com/jclyons52/eslint-go/rules/nomultipleemptylines"
	"github.com/jclyons52/eslint-go/rules/nomultispaces"
	"github.com/jclyons52/eslint-go/rules/nonewobject"
	"github.com/jclyons52/eslint-go/rules/nonewwrappers"
	"github.com/jclyons52/eslint-go/rules/noredeclare"
	"github.com/jclyons52/eslint-go/rules/noselfcompare"
	"github.com/jclyons52/eslint-go/rules/noshadow"
	"github.com/jclyons52/eslint-go/rules/nosparsearrays"
	"github.com/jclyons52/eslint-go/rules/nothrowliteral"
	"github.com/jclyons52/eslint-go/rules/notrailingspaces"
	"github.com/jclyons52/eslint-go/rules/noundef"
	"github.com/jclyons52/eslint-go/rules/nounsafenegation"
	"github.com/jclyons52/eslint-go/rules/nounusedvars"
	"github.com/jclyons52/eslint-go/rules/novar"
	"github.com/jclyons52/eslint-go/rules/nowhitespacebeforeproperty"
	"github.com/jclyons52/eslint-go/rules/preferconst"
	"github.com/jclyons52/eslint-go/rules/quotes"
	"github.com/jclyons52/eslint-go/rules/semi"
	"github.com/jclyons52/eslint-go/rules/semispacing"
	"github.com/jclyons52/eslint-go/rules/spaceinfixops"
	"github.com/jclyons52/eslint-go/rules/useisnan"
	"github.com/jclyons52/eslint-go/rules/validtypeof"
	"github.com/jclyons52/eslint-go/rules/yoda"
)

// registry is every ported rule, generated from rules/*/.
var registry = []eslint.Rule{
	commadangle.Rule,                // comma-dangle: 83 oracle cases
	curly.Rule,                      // curly: 56 oracle cases
	dotnotation.Rule,                // dot-notation: 63 oracle cases
	eollast.Rule,                    // eol-last: 39 oracle cases
	eqeqeq.Rule,                     // eqeqeq: 87 oracle cases
	noalert.Rule,                    // no-alert: 48 oracle cases
	noarrayconstructor.Rule,         // no-array-constructor: 33 oracle cases
	nocaller.Rule,                   // no-caller: 30 oracle cases
	nocondassign.Rule,               // no-cond-assign: 38 oracle cases
	noconsole.Rule,                  // no-console: 33 oracle cases
	nodebugger.Rule,                 // no-debugger: 16 oracle cases
	nodupeargs.Rule,                 // no-dupe-args: 33 oracle cases
	nodupekeys.Rule,                 // no-dupe-keys: 17 oracle cases
	noduplicatecase.Rule,            // no-duplicate-case: 49 oracle cases
	noelsereturn.Rule,               // no-else-return: 52 oracle cases
	noempty.Rule,                    // no-empty: 28 oracle cases
	noeval.Rule,                     // no-eval: 102 oracle cases
	noextrabooleancast.Rule,         // no-extra-boolean-cast: 58 oracle cases
	noextrasemi.Rule,                // no-extra-semi: 63 oracle cases
	nofloatingdecimal.Rule,          // no-floating-decimal: 32 oracle cases
	nofuncassign.Rule,               // no-func-assign: 33 oracle cases
	nolonelyif.Rule,                 // no-lonely-if: 40 oracle cases
	nomixedspacesandtabs.Rule,       // no-mixed-spaces-and-tabs: 44 oracle cases
	nomultipleemptylines.Rule,       // no-multiple-empty-lines: 44 oracle cases
	nomultispaces.Rule,              // no-multi-spaces: 42 oracle cases
	nonewobject.Rule,                // no-new-object: 33 oracle cases
	nonewwrappers.Rule,              // no-new-wrappers: 31 oracle cases
	noredeclare.Rule,                // no-redeclare: 43 oracle cases
	noselfcompare.Rule,              // no-self-compare: 63 oracle cases
	noshadow.Rule,                   // no-shadow: 54 oracle cases
	nosparsearrays.Rule,             // no-sparse-arrays: 22 oracle cases
	nothrowliteral.Rule,             // no-throw-literal: 44 oracle cases
	notrailingspaces.Rule,           // no-trailing-spaces: 22 oracle cases
	noundef.Rule,                    // no-undef: 24 oracle cases
	nounsafenegation.Rule,           // no-unsafe-negation: 52 oracle cases
	nounusedvars.Rule,               // no-unused-vars: 195 oracle cases
	novar.Rule,                      // no-var: 69 oracle cases
	nowhitespacebeforeproperty.Rule, // no-whitespace-before-property: 45 oracle cases
	preferconst.Rule,                // prefer-const: 55 oracle cases
	quotes.Rule,                     // quotes: 77 oracle cases
	semi.Rule,                       // semi: 132 oracle cases
	semispacing.Rule,                // semi-spacing: 69 oracle cases
	spaceinfixops.Rule,              // space-infix-ops: 55 oracle cases
	useisnan.Rule,                   // use-isnan: 57 oracle cases
	validtypeof.Rule,                // valid-typeof: 78 oracle cases
	yoda.Rule,                       // yoda: 76 oracle cases
}

// unverified lists rule packages that are present but have no parity test
// yet, so they are deliberately not registered.
var unverified = []string{}
